"use client";

import { useState } from "react";

export default function BusinessPage() {
  const [activeTab, setActiveTab] = useState<"model" | "market">("model");

  return (
    <div className="min-h-screen p-6 sm:p-10 mesh-bg">
      <div className="max-w-4xl mx-auto">
        
        {/* Header */}
        <div className="mb-10 animate-fade-in-up" style={{ opacity: 0 }}>
          <h1 className="text-3xl sm:text-4xl font-display text-text-primary mb-2 tracking-tight">Business Intelligence</h1>
          <p className="text-text-secondary">Monetization strategy and Total Addressable Market</p>
        </div>

        {/* Tabs */}
        <div className="flex gap-2 mb-8 p-1 rounded-xl glass w-full sm:w-fit animate-fade-in-up" style={{ opacity: 0, animationDelay: '0.1s' }}>
          <button 
            onClick={() => setActiveTab("model")}
            className={`flex-1 sm:px-8 py-2.5 text-sm font-medium rounded-lg transition-all ${activeTab === "model" ? 'bg-action text-canvas shadow-lg' : 'text-text-secondary hover:text-text-primary'}`}
          >
            Business Model
          </button>
          <button 
            onClick={() => setActiveTab("market")}
            className={`flex-1 sm:px-8 py-2.5 text-sm font-medium rounded-lg transition-all ${activeTab === "market" ? 'bg-action text-canvas shadow-lg' : 'text-text-secondary hover:text-text-primary'}`}
          >
            Market Size (TAM)
          </button>
        </div>

        {activeTab === "model" && (
          <div className="space-y-6 animate-fade-in-up" style={{ opacity: 0, animationDelay: '0.15s' }}>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="glass p-6 rounded-2xl md:col-span-2 relative overflow-hidden border border-action/20">
                <div className="absolute -right-20 -top-20 w-64 h-64 bg-action/10 blur-3xl rounded-full"></div>
                <h2 className="text-sm font-mono uppercase tracking-widest text-text-muted mb-6">B2B Aggregator SaaS</h2>
                <div className="flex flex-col gap-6">
                  
                  <div className="flex gap-4 items-start">
                    <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-action to-action-deep flex items-center justify-center shrink-0">
                      <svg className="w-5 h-5 text-canvas" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                    </div>
                    <div>
                      <h3 className="text-lg font-display text-text-primary mb-1">Per-Dispatch Transaction Fee</h3>
                      <p className="text-sm text-text-secondary leading-relaxed">Ripenly charges a 1.5% micro-commission on the realized value difference (the ERV alpha) generated by our routing recommendations.</p>
                    </div>
                  </div>

                  <div className="flex gap-4 items-start">
                    <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-action to-action-deep flex items-center justify-center shrink-0">
                      <svg className="w-5 h-5 text-canvas" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" /></svg>
                    </div>
                    <div>
                      <h3 className="text-lg font-display text-text-primary mb-1">Wholesale Analytics Dashboard</h3>
                      <p className="text-sm text-text-secondary leading-relaxed">Large-scale aggregators and co-ops pay a $50/mo subscription for macro-level supply insights and predictive forecasting API access.</p>
                    </div>
                  </div>

                </div>
              </div>

              <div className="glass p-6 rounded-2xl flex flex-col justify-center text-center">
                <span className="text-[10px] font-mono uppercase tracking-widest text-text-muted mb-2">Projected Unit Economics</span>
                <span className="text-5xl font-display font-bold text-text-primary mb-1">6.2x</span>
                <span className="text-xs text-text-secondary mb-6">LTV to CAC Ratio</span>
                
                <div className="w-full h-px bg-border mb-6"></div>
                
                <div className="flex justify-between items-center text-sm">
                  <span className="text-text-secondary">Avg Deal Size</span>
                  <span className="font-mono text-text-primary">$4,200/yr</span>
                </div>
                <div className="flex justify-between items-center text-sm mt-3">
                  <span className="text-text-secondary">Gross Margin</span>
                  <span className="font-mono text-text-primary">82%</span>
                </div>
              </div>
            </div>

            <div className="glass p-8 rounded-2xl">
              <h3 className="text-sm font-mono uppercase tracking-widest text-text-muted mb-8">Revenue Growth Simulation</h3>
              
              {/* Mock Chart Area */}
              <div className="relative h-48 w-full flex items-end gap-2 justify-between">
                {[12, 18, 24, 38, 55, 78, 105, 140, 190, 260, 340, 450].map((val, i) => (
                  <div key={i} className="w-full relative group flex justify-center">
                    <div 
                      className="w-full bg-gradient-to-t from-action/20 to-action rounded-t-sm opacity-80 group-hover:opacity-100 transition-opacity"
                      style={{ height: `${(val / 450) * 100}%` }}
                    ></div>
                    <span className="absolute -top-6 text-[10px] font-mono opacity-0 group-hover:opacity-100 transition-opacity text-action">
                      ${val}k
                    </span>
                  </div>
                ))}
                
                {/* Grid lines */}
                <div className="absolute inset-0 pointer-events-none border-b border-border">
                  <div className="absolute top-0 w-full h-px bg-border/50 border-dashed border-b"></div>
                  <div className="absolute top-1/2 w-full h-px bg-border/50 border-dashed border-b"></div>
                </div>
              </div>
              
              <div className="flex justify-between mt-4 text-xs font-mono text-text-muted">
                <span>Month 1</span>
                <span>Month 6</span>
                <span>Month 12</span>
              </div>
            </div>

          </div>
        )}

        {activeTab === "market" && (
          <div className="space-y-6 animate-fade-in-up" style={{ opacity: 0, animationDelay: '0.15s' }}>
            
            <div className="glass p-8 rounded-2xl relative overflow-hidden">
              <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-action/5 via-transparent to-transparent pointer-events-none"></div>
              
              <div className="flex flex-col items-center text-center max-w-2xl mx-auto mb-12">
                <h2 className="text-3xl font-display text-text-primary mb-4 tracking-tight">Total Addressable Market</h2>
                <p className="text-sm text-text-secondary leading-relaxed">
                  Post-harvest loss in developing nations is a massive inefficiency. Ripenly captures value by routing perishable goods before they spoil.
                </p>
              </div>

              {/* Concentric Circles UI */}
              <div className="relative w-full max-w-md mx-auto aspect-square flex items-center justify-center">
                
                {/* TAM */}
                <div className="absolute inset-0 rounded-full border border-border/50 bg-glass-strong/30 flex flex-col items-center justify-start pt-10">
                  <span className="text-sm font-medium text-text-primary">TAM</span>
                  <span className="font-mono font-bold text-lg text-text-muted">$3.2 Billion</span>
                  <span className="text-[10px] uppercase text-text-muted/70 mt-1">Global Spoilage Mkt</span>
                </div>

                {/* SAM */}
                <div className="absolute w-[70%] h-[70%] rounded-full border border-action/20 bg-action/5 flex flex-col items-center justify-start pt-8 z-10 shadow-[inset_0_0_40px_rgba(40,167,69,0.05)]">
                  <span className="text-sm font-medium text-text-primary">SAM</span>
                  <span className="font-mono font-bold text-lg text-text-primary">$420 Million</span>
                  <span className="text-[10px] uppercase text-text-muted/70 mt-1">South Asia Ag-Logistics</span>
                </div>

                {/* SOM */}
                <div className="absolute w-[40%] h-[40%] rounded-full bg-gradient-to-br from-action to-action-deep flex flex-col items-center justify-center z-20 shadow-xl shadow-action/30 text-canvas">
                  <span className="text-sm font-medium opacity-90">SOM</span>
                  <span className="font-mono font-bold text-2xl">$18M</span>
                  <span className="text-[10px] uppercase opacity-70 mt-1 text-center leading-tight">Bangladesh<br/>Year 1-3</span>
                </div>

              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
              {[
                { label: "Annual Spoilage Value", value: "$4B+", sub: "In South Asia alone" },
                { label: "Aggregator Co-ops", value: "12,000+", sub: "Target B2B customers" },
                { label: "Est. Savings Generated", value: "22%", sub: "Via dynamic ERV routing" }
              ].map((stat, i) => (
                <div key={i} className="glass p-6 rounded-2xl text-center">
                  <p className="text-text-secondary text-xs uppercase tracking-wider mb-2">{stat.label}</p>
                  <p className="text-3xl font-display font-bold text-text-primary mb-1">{stat.value}</p>
                  <p className="text-text-muted text-xs">{stat.sub}</p>
                </div>
              ))}
            </div>

          </div>
        )}

      </div>
    </div>
  );
}
