spring.application.name=backend
spring.config.import=optional:file:.env[.properties]

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ripenly}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# SQL Initialization Configuration
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Hibernate / JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
